/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.massdown.views;

import com.massdown.core.Serie;
import com.massdown.gestordescarga.GestorDescargas;
import com.sun.java.swing.plaf.motif.MotifProgressBarUI;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.JToggleButton;
import javax.swing.plaf.ProgressBarUI;
import javax.swing.plaf.ScrollBarUI;
import javax.swing.plaf.metal.MetalScrollBarUI;

/**
 *
 * @author Guillermo
 */
public class MainWindow extends javax.swing.JFrame {
    
    public GestorDescargas gestorDescargas = new GestorDescargas();
    
    public MainWindow() {
        initComponents();
        MostarPBar(false);
        pbarPrincipal.setUI(new MotifProgressBarUI());
        this.IrATab(btnSearch);
        
        
         pnlPrincipalScroll.getVerticalScrollBar().setUnitIncrement(30);
         ScrollBarUI scrollBarStyle = new MetalScrollBarUI(){
            @Override
            protected JButton createDecreaseButton(int orientation) {
                JButton button = super.createDecreaseButton(orientation);
                button.setBackground(new Color(56,56,56));
                return button;
            }

            @Override
            protected JButton createIncreaseButton(int orientation) {
                JButton button = super.createIncreaseButton(orientation);
                button.setBackground(new Color(56,56,56));
                return button;
            }
        };
        pnlPrincipalScroll.getVerticalScrollBar().setUI(scrollBarStyle);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenu = new javax.swing.JToolBar();
        jLabel3 = new javax.swing.JLabel();
        btnDescargas = new javax.swing.JToggleButton();
        btnSearch = new javax.swing.JToggleButton();
        btnBiblioteca = new javax.swing.JToggleButton();
        lblParaIrAlTabSerie = new javax.swing.JLabel();
        txtBusqueda = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnAjustes = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        pnlPrincipalScroll = new javax.swing.JScrollPane();
        pnlPrincipal = new javax.swing.JPanel();
        pbarPrincipal = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("massdown");
        setIconImage(new ImageIcon(getClass().getResource("/com/massdown/img/icon.png")).getImage());
        setLocationByPlatform(true);

        pnlMenu.setBackground(new java.awt.Color(53, 50, 48));
        pnlMenu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlMenu.setFloatable(false);
        pnlMenu.setMaximumSize(new java.awt.Dimension(95, 93));

        jLabel3.setForeground(new java.awt.Color(53, 50, 48));
        jLabel3.setText("p");
        pnlMenu.add(jLabel3);

        btnDescargas.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnDescargas.setForeground(new java.awt.Color(255, 255, 255));
        btnDescargas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/massdown/img/descargas3.png"))); // NOI18N
        btnDescargas.setText("downloads");
        btnDescargas.setFocusable(false);
        btnDescargas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDescargas.setMaximumSize(new java.awt.Dimension(105, 71));
        btnDescargas.setPreferredSize(new java.awt.Dimension(105, 71));
        btnDescargas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDescargas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescargasActionPerformed(evt);
            }
        });
        pnlMenu.add(btnDescargas);

        btnSearch.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/massdown/img/search.png"))); // NOI18N
        btnSearch.setText("explore");
        btnSearch.setFocusable(false);
        btnSearch.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSearch.setMaximumSize(new java.awt.Dimension(85, 71));
        btnSearch.setPreferredSize(new java.awt.Dimension(85, 71));
        btnSearch.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        pnlMenu.add(btnSearch);

        btnBiblioteca.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnBiblioteca.setForeground(new java.awt.Color(255, 255, 255));
        btnBiblioteca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/massdown/img/videos.png"))); // NOI18N
        btnBiblioteca.setText("library");
        btnBiblioteca.setFocusable(false);
        btnBiblioteca.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBiblioteca.setMaximumSize(new java.awt.Dimension(85, 71));
        btnBiblioteca.setPreferredSize(new java.awt.Dimension(85, 71));
        btnBiblioteca.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBiblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBibliotecaActionPerformed(evt);
            }
        });
        pnlMenu.add(btnBiblioteca);

        lblParaIrAlTabSerie.setForeground(new java.awt.Color(53, 50, 48));
        lblParaIrAlTabSerie.setText("jLab");
        pnlMenu.add(lblParaIrAlTabSerie);

        txtBusqueda.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        txtBusqueda.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtBusqueda.setText("search series");
        txtBusqueda.setMargin(new java.awt.Insets(2, 10, 2, 2));
        txtBusqueda.setMaximumSize(new java.awt.Dimension(2147483647, 38));
        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyPressed(evt);
            }
        });
        pnlMenu.add(txtBusqueda);

        jLabel4.setForeground(new java.awt.Color(53, 50, 48));
        jLabel4.setText("jLab");
        pnlMenu.add(jLabel4);

        btnAjustes.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnAjustes.setForeground(new java.awt.Color(255, 255, 255));
        btnAjustes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/massdown/img/ajustes.png"))); // NOI18N
        btnAjustes.setText("settings");
        btnAjustes.setFocusable(false);
        btnAjustes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAjustes.setMaximumSize(new java.awt.Dimension(85, 71));
        btnAjustes.setPreferredSize(new java.awt.Dimension(85, 71));
        btnAjustes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAjustes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjustesActionPerformed(evt);
            }
        });
        pnlMenu.add(btnAjustes);

        jLabel5.setForeground(new java.awt.Color(53, 50, 48));
        jLabel5.setText("p");
        pnlMenu.add(jLabel5);

        pnlPrincipalScroll.setBackground(new java.awt.Color(56, 56, 56));
        pnlPrincipalScroll.setBorder(null);
        pnlPrincipalScroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        pnlPrincipal.setBackground(new java.awt.Color(56, 56, 56));
        pnlPrincipal.setLayout(new java.awt.CardLayout());
        pnlPrincipalScroll.setViewportView(pnlPrincipal);

        pbarPrincipal.setToolTipText("Loading");
        pbarPrincipal.setBorderPainted(false);
        pbarPrincipal.setIndeterminate(true);
        pbarPrincipal.setMaximumSize(new java.awt.Dimension(32767, 3));
        pbarPrincipal.setMinimumSize(new java.awt.Dimension(10, 3));
        pbarPrincipal.setPreferredSize(new java.awt.Dimension(146, 3));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 836, Short.MAX_VALUE)
            .addComponent(pnlPrincipalScroll)
            .addComponent(pbarPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlPrincipalScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(pbarPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAjustesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjustesActionPerformed
        this.IrATab(btnAjustes);
    }//GEN-LAST:event_btnAjustesActionPerformed

    private void btnDescargasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescargasActionPerformed
        this.IrATab(btnDescargas);
    }//GEN-LAST:event_btnDescargasActionPerformed

    private void btnBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBibliotecaActionPerformed
        this.IrATab(btnBiblioteca);
    }//GEN-LAST:event_btnBibliotecaActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        this.IrATab(btnSearch);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtBusquedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyPressed
        //Si es intro ejecutamos acciones si no, nada.
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {           
            IrATab(lblParaIrAlTabSerie);
        }
    }//GEN-LAST:event_txtBusquedaKeyPressed
    
    public void MostarPBar(boolean siono) {
        if(siono) {
            pbarPrincipal.setVisible(true);
        } else {
            pbarPrincipal.setVisible(false);
        }
    }
    
    public void IrATab(Component tabPulsado) {
        
        
        pnlPrincipal.removeAll();
        
        switch(pnlMenu.getComponentIndex(tabPulsado)) {
            //TAB DESCARGAS
            case 1:
                pnlPrincipal.add(new DownloadsPanel(this));
                
                btnAjustes.setSelected(false);
                btnBiblioteca.setSelected(false);
                btnSearch.setSelected(false);
                break;
            //TAB BUSQUEDA
            case 2:
                btnSearch.setSelected(true);
                btnDescargas.setSelected(false);
                btnAjustes.setSelected(false);
                btnBiblioteca.setSelected(false);
                
                
                pnlPrincipal.add(new SearchPanel(this, txtBusqueda.getText()));
                break;
            case 4:
                btnSearch.setSelected(true);
                btnDescargas.setSelected(false);
                btnAjustes.setSelected(false);
                btnBiblioteca.setSelected(false);
                
                
                pnlPrincipal.add(new SeriePanel(this, txtBusqueda.getText()));
                break;
            //TAB BLIBLIOTECA    
            case 3:
                btnDescargas.setSelected(false);
                btnAjustes.setSelected(false);
                btnSearch.setSelected(false);
                pnlPrincipal.add(new LibraryPanel());
                break;
            //TAB SETTINGS
            case 7:
                pnlPrincipal.add(new SettingsPanel());
                
                btnDescargas.setSelected(false);
                btnBiblioteca.setSelected(false);
                btnSearch.setSelected(false);
                break;
        }
        pnlPrincipal.revalidate();
        pnlPrincipal.repaint();
    }

    public JToggleButton getBtnDescargas() {
        return btnDescargas;
    }

    public JPanel getPnlPrincipal() {
        return pnlPrincipal;
    }

    public JTextField getTxtBusqueda() {
        return txtBusqueda;
    }

    public JToggleButton getBtnAjustes() {
        return btnAjustes;
    }

    public JLabel getLblParaIrAlTabSerie() {
        return lblParaIrAlTabSerie;
    }
    
    
    
    public JToggleButton getBtnBiblioteca() {
        return btnBiblioteca;
    }

    public JToggleButton getBtnSearch() {
        return btnSearch;
    }

    public void ActualizarLabelDescargas() {
        btnDescargas.setText("downloads "+"("+gestorDescargas.getDescargasEnCurso().size()+")");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAjustes;
    private javax.swing.JToggleButton btnBiblioteca;
    private javax.swing.JToggleButton btnDescargas;
    private javax.swing.JToggleButton btnSearch;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblParaIrAlTabSerie;
    private javax.swing.JProgressBar pbarPrincipal;
    private javax.swing.JToolBar pnlMenu;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JScrollPane pnlPrincipalScroll;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables
}
