/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.massdown.views;

import com.massdown.GestorDescargas;
import com.massdown.Serie;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JToggleButton;
import javax.swing.UIManager;

/**
 *
 * @author Guillermo
 */
public class MainWindow extends javax.swing.JFrame {
    
    public GestorDescargas gestorDescargas = new GestorDescargas();
    
    public MainWindow() {
        initComponents();
        MostarPBar(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenu = new javax.swing.JToolBar();
        jLabel3 = new javax.swing.JLabel();
        btnDescargas = new javax.swing.JToggleButton();
        btnSearch = new javax.swing.JToggleButton();
        btnFavoritos = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        txtBusqueda = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnAjustes = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        pnlPrincipalScroll = new javax.swing.JScrollPane();
        pnlPrincipal = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pbarPrincipal = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("massdown");
        setIconImage(new ImageIcon(getClass().getResource("/com/massdown/img/icon.png")).getImage());
        setLocationByPlatform(true);

        pnlMenu.setBackground(new java.awt.Color(53, 50, 48));
        pnlMenu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlMenu.setFloatable(false);
        pnlMenu.setMaximumSize(new java.awt.Dimension(95, 93));

        jLabel3.setForeground(new java.awt.Color(53, 50, 48));
        jLabel3.setText("p");
        pnlMenu.add(jLabel3);

        btnDescargas.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnDescargas.setForeground(new java.awt.Color(255, 255, 255));
        btnDescargas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/massdown/img/descargas.png"))); // NOI18N
        btnDescargas.setText("downloads");
        btnDescargas.setFocusable(false);
        btnDescargas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDescargas.setMaximumSize(new java.awt.Dimension(85, 71));
        btnDescargas.setPreferredSize(new java.awt.Dimension(85, 71));
        btnDescargas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDescargas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescargasActionPerformed(evt);
            }
        });
        pnlMenu.add(btnDescargas);

        btnSearch.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/massdown/img/search.png"))); // NOI18N
        btnSearch.setText("search");
        btnSearch.setFocusable(false);
        btnSearch.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSearch.setMaximumSize(new java.awt.Dimension(85, 71));
        btnSearch.setPreferredSize(new java.awt.Dimension(85, 71));
        btnSearch.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        pnlMenu.add(btnSearch);

        btnFavoritos.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnFavoritos.setForeground(new java.awt.Color(255, 255, 255));
        btnFavoritos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/massdown/img/favs.png"))); // NOI18N
        btnFavoritos.setText("favorites");
        btnFavoritos.setFocusable(false);
        btnFavoritos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFavoritos.setMaximumSize(new java.awt.Dimension(85, 71));
        btnFavoritos.setPreferredSize(new java.awt.Dimension(85, 71));
        btnFavoritos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFavoritos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFavoritosActionPerformed(evt);
            }
        });
        pnlMenu.add(btnFavoritos);

        jLabel1.setForeground(new java.awt.Color(53, 50, 48));
        jLabel1.setText("jLab");
        pnlMenu.add(jLabel1);

        txtBusqueda.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        txtBusqueda.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtBusqueda.setText("enter a serie");
        txtBusqueda.setMargin(new java.awt.Insets(2, 10, 2, 2));
        txtBusqueda.setMaximumSize(new java.awt.Dimension(2147483647, 38));
        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyPressed(evt);
            }
        });
        pnlMenu.add(txtBusqueda);

        jLabel4.setForeground(new java.awt.Color(53, 50, 48));
        jLabel4.setText("jLab");
        pnlMenu.add(jLabel4);

        btnAjustes.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnAjustes.setForeground(new java.awt.Color(255, 255, 255));
        btnAjustes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/massdown/img/ajustes.png"))); // NOI18N
        btnAjustes.setText("settings");
        btnAjustes.setFocusable(false);
        btnAjustes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAjustes.setMaximumSize(new java.awt.Dimension(85, 71));
        btnAjustes.setPreferredSize(new java.awt.Dimension(85, 71));
        btnAjustes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAjustes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjustesActionPerformed(evt);
            }
        });
        pnlMenu.add(btnAjustes);

        jLabel5.setForeground(new java.awt.Color(53, 50, 48));
        jLabel5.setText("p");
        pnlMenu.add(jLabel5);

        pnlPrincipalScroll.setBackground(new java.awt.Color(56, 56, 56));
        pnlPrincipalScroll.setBorder(null);

        pnlPrincipal.setBackground(new java.awt.Color(56, 56, 56));
        pnlPrincipal.setLayout(new java.awt.CardLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("loading...");
        pnlPrincipal.add(jLabel2, "card2");

        pnlPrincipalScroll.setViewportView(pnlPrincipal);

        pbarPrincipal.setIndeterminate(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE)
            .addComponent(pnlPrincipalScroll)
            .addComponent(pbarPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlPrincipalScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(pbarPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAjustesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjustesActionPerformed
        this.IrATab(btnAjustes);
    }//GEN-LAST:event_btnAjustesActionPerformed

    private void btnDescargasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescargasActionPerformed
        this.IrATab(btnDescargas);
    }//GEN-LAST:event_btnDescargasActionPerformed

    private void btnFavoritosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFavoritosActionPerformed
        this.IrATab(btnFavoritos);
    }//GEN-LAST:event_btnFavoritosActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        this.IrATab(btnSearch);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtBusquedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyPressed
        //Si es intro ejecutamos acciones si no, nada.
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {           
            IrATab(btnSearch);
        }
    }//GEN-LAST:event_txtBusquedaKeyPressed
    
    public void MostarPBar(boolean siono) {
        if(siono) {
            pbarPrincipal.setVisible(true);
        } else {
            pbarPrincipal.setVisible(false);
        }
    }
    
    private void IrATab(JToggleButton tabPulsado) {
        
        
        pnlPrincipal.removeAll();
        
        switch(tabPulsado.getText()) {
            case "settings":
                pnlPrincipal.add(new SettingsPanel());
                
                btnDescargas.setSelected(false);
                btnFavoritos.setSelected(false);
                btnSearch.setSelected(false);
                break;
            case "downloads":
                pnlPrincipal.add(new DownloadsPanel(this));
                
                btnAjustes.setSelected(false);
                btnFavoritos.setSelected(false);
                btnSearch.setSelected(false);
                break;
            case "favorites":
                btnDescargas.setSelected(false);
                btnAjustes.setSelected(false);
                btnSearch.setSelected(false);
                break;
            case "search":
                btnSearch.setSelected(true);
                btnDescargas.setSelected(false);
                btnAjustes.setSelected(false);
                btnFavoritos.setSelected(false);
                
                
                pnlPrincipal.add(new SeriePanel(this, txtBusqueda.getText()));
                break;
        }
        pnlPrincipal.revalidate();
        pnlPrincipal.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAjustes;
    private javax.swing.JToggleButton btnDescargas;
    private javax.swing.JToggleButton btnFavoritos;
    private javax.swing.JToggleButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JProgressBar pbarPrincipal;
    private javax.swing.JToolBar pnlMenu;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JScrollPane pnlPrincipalScroll;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables
}
