/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package es.gmarco.massdown.forms;

import es.gmarco.massdown.clases_escalables.MetodosUtiles;
import es.gmarco.massdown.superclases.Main;
import java.io.IOException;
import java.net.MalformedURLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;

/**
 *
 * @author Guillermo
 */
public class CatalogoForm extends javax.swing.JFrame {

    private Main programaPrincipal;
    
    public CatalogoForm(Main mn) {
        this.programaPrincipal = mn;
        initComponents();
        setVisible(true);
        pbar.setVisible(false);
        
        new Thread() {

            @Override
            public void run() {
                try {
                    ObtenerListaDeSeriesDestacadas();
                } catch (MalformedURLException ex) {
                    Logger.getLogger(CatalogoForm.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(CatalogoForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
        }.start();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        lblCargaCaps = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstDestacados = new javax.swing.JList();
        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList5 = new javax.swing.JList();
        pbar = new javax.swing.JProgressBar();

        setTitle("Catalogo de series");
        setIconImage(new ImageIcon(getClass().getResource("/es/gmarco/massdown/recursos/icon.png")).getImage());

        jPanel5.setBackground(new java.awt.Color(30, 30, 30));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setPreferredSize(new java.awt.Dimension(210, 270));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Series populares");

        jSeparator4.setBackground(new java.awt.Color(239, 64, 54));
        jSeparator4.setForeground(new java.awt.Color(239, 64, 54));

        lblCargaCaps.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblCargaCaps.setForeground(new java.awt.Color(255, 255, 255));
        lblCargaCaps.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        lstDestacados.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        lstDestacados.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstDestacados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstDestacadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstDestacados);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCargaCaps, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 388, Short.MAX_VALUE)
                        .addComponent(lblCargaCaps, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(53, 50, 48));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Proximamente..." }));
        jComboBox1.setMinimumSize(new java.awt.Dimension(44, 44));
        jComboBox1.setPreferredSize(new java.awt.Dimension(32, 28));

        jTabbedPane1.setName("jkjlk\nhhjkll\njol"); // NOI18N

        jList5.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Proximamente..." };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(jList5);

        jTabbedPane1.addTab("Proximamente...", jScrollPane5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(pbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lstDestacadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstDestacadosMouseClicked
        programaPrincipal.setTextoTxtSerie((String) lstDestacados.getSelectedValue());
        programaPrincipal.CargarSerie((String) lstDestacados.getSelectedValue());
    }//GEN-LAST:event_lstDestacadosMouseClicked

    private ArrayList<String> ObtenerListaDeSeriesDestacadas() throws MalformedURLException, IOException {
        
        String codigoFuente = MetodosUtiles.ObtenerCodigoFuente("http://www.seriesyonkis.com/series-mas-vistas")[1];
        int nodo = codigoFuente.indexOf("vistas ayer</h1>");
        
        DefaultListModel lst = new DefaultListModel();
                
        while(nodo >= 0) {
            
            String[] serie = MetodosUtiles.ObtenerCadenaEntreTags(codigoFuente, 
                    "<img width=\"100\" height=\"144\" class=\"img-shadow\"", 
                    "/> </a> <strong>  <a href=\"", 55, 0, nodo);
            nodo = Integer.parseInt(serie[1]);
            serie[0] = serie[0].replaceAll("-", " ")
                    .substring(serie[0].indexOf("\" alt=\""))
                    .replaceAll("\" alt=\"", "")
                    .replaceAll("\" ", "");
            
            String[] palabrasDelTitulo = serie[0].split(" ");
            

            for(int i = 0 ; i < palabrasDelTitulo.length ; i++) {
                char[] letrasDeLaPalabra = palabrasDelTitulo[i].toCharArray();  
                if(letrasDeLaPalabra.length >= 0) {
                    letrasDeLaPalabra[0] = Character.toUpperCase(letrasDeLaPalabra[0]);                
                    palabrasDelTitulo[i] = String.copyValueOf(letrasDeLaPalabra);
                }
            }                       
            
            for(String palabra : palabrasDelTitulo) {
                System.out.println(palabra.toString());
            }
            
            serie[0] = Arrays.toString(palabrasDelTitulo)
                                  .replace(",", "")  
                                  .replace("[", "")  
                                  .replace("]", "");
            
            System.out.println(serie[0]);
            if(lst.contains(serie[0])) {
                break;
            }
                
            lst.addElement(serie[0]);
                                                              
        }
        
        lstDestacados.setModel(lst);
        
        
        return null;        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblCargaCaps;
    private javax.swing.JList lstDestacados;
    private javax.swing.JProgressBar pbar;
    // End of variables declaration//GEN-END:variables
}
